### ISSUE TITLE
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`

### ISSUE THREAD

**Issue by DullCube** [dunbar12138/pix2pix3D#13]
Hi, on my 4090 GPU, I had successful implement `environment.yml`, But Now I am having problem while generating samples with `python applications/generate_samples.py --network checkpoints/pix2pix3d_seg2cat.pkl --outdir examples --random_seed 1 --cfg seg2cat --input_id 1666`.
`Setting up PyTorch plugin "bias_act_plugin"... Done.
Setting up PyTorch plugin "upfirdn2d_plugin"... Done.
Traceback (most recent call last):
  File "/home/ysh/NN01/pix2pix3D/applications/generate_samples.py", line 128, in <module>
    main()
  File "/home/ysh/NN01/pix2pix3D/applications/generate_samples.py", line 114, in main
    out = G.synthesis(ws, input_pose, noise_mode='const', neural_rendering_resolution=neural_rendering_resolution)
  File "<string>", line 946, in synthesis
  File "/home/ysh/.conda/envs/pix2pix3d/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ysh/NN01/pix2pix3D/./training/volumetric_rendering/renderer.py", line 109, in forward
    out = self.run_model(planes, decoder, sample_coordinates, sample_directions, rendering_options)
  File "/home/ysh/NN01/pix2pix3D/./training/volumetric_rendering/renderer.py", line 143, in run_model
    sampled_features = sample_from_planes(self.plane_axes, planes, sample_coordinates, padding_mode='zeros', box_warp=options['box_warp'])
  File "/home/ysh/NN01/pix2pix3D/./training/volumetric_rendering/renderer.py", line 63, in sample_from_planes
    projected_coordinates = project_onto_planes(plane_axes, coordinates).unsqueeze(1)
  File "/home/ysh/NN01/pix2pix3D/./training/volumetric_rendering/renderer.py", line 51, in project_onto_planes
    inv_planes = torch.linalg.inv(planes).unsqueeze(0).expand(N, -1, -1, -1).reshape(N*n_planes, 3, 3)
RuntimeError: CUDA error: operation not supported when calling `cusparseCreate(handle)`
`

**Comment by God-YYB** [comment]
Have you solved it yet
