### ISSUE TITLE
UnboundLocalError: local variable 'wandb' referenced before assignment

### ISSUE THREAD

**Issue by Ysz2022** [dunbar12138/pix2pix3D#28]
Good work!

When I use train_scripts/shapenet_edge.sh for training, I meet this bug:
Training for 25000 kimg...

tick 0     kimg 0.0      time 1m 29s       sec/tick 8.1     sec/kimg 253.78  maintenance 81.2   cpumem 6.00   gpumem 19.10  reserved 21.52  augment 0.000
Traceback (most recent call last):
  File "/userhome/pix2pix3D-main/train.py", line 540, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/userhome/pix2pix3D-main/train.py", line 534, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "/userhome/pix2pix3D-main/train.py", line 112, in launch_training
    torch.multiprocessing.spawn(
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/envs/pix2pix3d/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/userhome/pix2pix3D-main/train.py", line 57, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/userhome/pix2pix3D-main/training/training_loop.py", line 690, in training_loop
    log_table(G_ema, grid_z, grid_i, grid_c, grid_m, grid_p, mask_type=training_set_kwargs.data_type, global_step=cur_nimg//1000, device=device, wandb=wandb)
UnboundLocalError: local variable 'wandb' referenced before assignment

Have you ever meet this wrong? Could you please tell me the possible reason? Thank you very much!

**Comment by dunbar12138** [comment]
Hi, this is because `wandb` is still used even if `wandb_log` is set to `False`. I have fixed this bug in the latest version. Could you pull and try it again?
