### ISSUE TITLE
raise AssertionError(f'Wrong size for dimension {idx}: got {size}, expected {ref_size}') AssertionError: Wrong size for dimension 1: got 0, expected 25

### ISSUE THREAD

**Issue by manoj-samal** [dunbar12138/pix2pix3D#35]
!python applications/generate_samples.py --network checkpoints/pix2pix3d_seg2cat.pkl --outdir examples --random_seed 1 --cfg seg2cat --input_id 2

was running in google colab

Traceback (most recent call last):
  File "/content/pix2pix3D/applications/generate_samples.py", line 128, in <module>
    main()
  File "/content/pix2pix3D/applications/generate_samples.py", line 113, in main
    ws = G.mapping(z, input_pose, {'mask': input_label, 'pose': input_pose})
  File "<string>", line 919, in mapping
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "<string>", line 361, in forward
  File "/content/pix2pix3D/./torch_utils/misc.py", line 97, in assert_shape
    raise AssertionError(f'Wrong size for dimension {idx}: got {size}, expected {ref_size}')
AssertionError: Wrong size for dimension 1: got 0, expected 25

raise AssertionError(f'Wrong size for dimension {idx}: got {size}, expected {ref_size}')
AssertionError: Wrong size for dimension 1: got 0, expected 25

**Comment by dunbar12138** [comment]
Thanks for your interest.

You need to have the dataset downloaded to inference using a test set input ID.
